
- name: display content 
  shell: |
    sudo apt install python3

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  template:
    src: "/home/circleci/project/artifact.tar.gz"
    dest: "~/web/artifact.tar.gz"
    
- name: tar archive dir 
  shell: |
    sudo apt install tar
    tar -xzvf artifact.tar.gz -C ~/web
- name: display content 
  shell: |
    ls ~/web    
# - name: Executing node
#   shell: |
#     pm2 start ~/web/index.js -f
