
- name: install python 
  shell: |
    sudo apt install python3

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  ansible.builtin.copy:
    src: "/home/circleci/project/artifact.tar.gz"
    dest: "~/web/artifact.tar.gz"
    
- name: tar archive dir 
  shell: |
    tar -xf ~/web/artifact.tar.gz -C ~/web
- name: display content 
  shell: |
    ls ~/web
    node -v
# - name: Executing node
#   shell: |
#     pm2 start ~/web/index.js -f
