

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  template:
    src: "~/project/artifact.tar.gz"
    dest: "~/web/artifact.tar.gz"
    
- name: tar archive dir 
  shell: |
    sudo apt install tar
    tar -xf artifact.tar.gz -C ~/web
    ls ~/web
- name: display content 
  shell: |
    ls ~/web    
# - name: Executing node
#   shell: |
#     pm2 start ~/web/index.js -f
